version: "3.9"

services:
  web:
    build: .
    container_name: email_web
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --log-level debug
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USE_TLS: "false"
    volumes:
      - .:/app
      - app_data:/app/data
    depends_on:
      - redis
      - mailhog

  worker_send:
    build: .
    container_name: email_worker_send
    command: >
      celery -A app.tasks.celery_app:celery_app
      worker -B -l info -Q control,send
    env_file:
      - .env
    environment:
      BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USE_TLS: "false"
    volumes:
      - .:/app
      - app_data:/app/data
    depends_on:
      - redis
      - mailhog

  worker_monitor:
    build: .
    container_name: email_worker_monitor
    command: >
      celery -A app.tasks.celery_app:celery_app
      worker -l info -Q celery,monitor
    env_file:
      - .env
    environment:
      BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USE_TLS: "false"
    volumes:
      - .:/app
      - app_data:/app/data
    depends_on:
      - redis
      - mailhog

  redis:
    image: redis:7-alpine
    container_name: email_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: email_mailhog
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP

volumes:
  app_data: